play file updated
Richu98/team-2-cricket-match-frontend pull request #7
Opened 2020-06-10 08:34 UTC by Sheetal1012

2020-06-10 14:35 UTC, tarunkethwalia requested changes
Please update the required changes.

2020-06-10 14:35 UTC, tarunkethwalia commented on src/Components/Match/Play.js
> +  state={ANames:[],Aplayers:[],Bplayers:[],BNames:[],scoreA:0,totalA:0,scoreB:0,totalB:0,incrementA:0,incrementB:0}
Proper indentation is required.

2020-06-10 14:35 UTC, tarunkethwalia commented on src/Components/Match/Play.js
> +      const runa = Math.floor(Math.random()*6);
Please make A and B capital in runa and runb

2020-06-12 12:07 UTC, merged

2020-06-12 12:30 UTC, Richu98 commented
Branch name should be TOSSF-6 @Sheetal1012